kind: Deployment
apiVersion: apps/v1
metadata:
   name: deployments
spec:
   replicas: 2
   selector:     
    matchLabels:
     name: dep1
   template:
     metadata:
       name: testpod
       labels:
        name: dep1
     spec:
      containers:
      - name: c1
# image: ubuntu
# command: ["/bin/bash", "-c", "while true; do echo Shubham Chouhan; sleep 5; done"]
        image: centos
        command: ["/bin/bash", "-c", "while true; do echo Chouhan Shubham; sleep 5; done"]