# Generated by Django 5.0.1 on 2024-02-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=255)),
                ('configuration', models.JSONField()),
            ],
        ),
    ]
