kind: ReplicationController
apiVersion: v1
metadata:
  name: myrc
spec:
  replicas: 3
  selector:
    app: example-app
  template:
    metadata:
      name: myrc1
      labels:
        app: example-app
    spec:
      containers:
        - name: container-1
          image: ubuntu
          command: ["/bin/bash", "-c", "echo Shubham Chouhan; sleep 500"]