apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: container-1
          image: ubuntu
          command: ["/bin/bash", "-c", "echo Shubham Chouhan; sleep 500"]
