apiVersion: batch/v1
kind: CronJob
metadata:
 name: shub
spec:
 schedule: "* * * * *"
 jobTemplate:
   spec:
     template:
       spec:
         containers:
         - image: ubuntu
           name: bhupi
           command: ["/bin/bash", "-c", "echo Shubham Chouhan; sleep 5"]
         restartPolicy: Never